import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const SUPABASE_URL='https://ajldblvvlbvmgejrmhyj.supabase.co';
const SUPABASE_KEY='sb_publishable_D22GtKy7nDvnLv7LeBL1SA_1_ZGbN7d';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
const state={user:null,profile:null,profiles:[],entitlements:[],threads:[],messages:[],brands:[],settings:[],faqs:[],audit:[],selectedThread:null,loadErrors:[],canned:[],incidents:[],deliveries:[]};
const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];

function toast(message){const n=$('#toast');n.textContent=message;n.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>n.classList.remove('show'),3000)}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function formatDate(value,withTime=true){if(!value)return '–';return new Intl.DateTimeFormat('nl-NL',withTime?{dateStyle:'short',timeStyle:'short'}:{dateStyle:'medium'}).format(new Date(value))}
function profileFor(id){return state.profiles.find((p)=>p.id===id)}
function activeEntitlement(userId){const now=Date.now();return state.entitlements.find((e)=>e.user_id===userId&&e.product_id==='paskluis_plus'&&!e.revoked_at&&(!e.expires_at||new Date(e.expires_at).getTime()>now))}
function roleLabel(role){return role==='admin'?'Beheerder':role==='support'?'Klantenservice':'Gebruiker'}
function statusLabel(status){return status==='closed'?'Gesloten':status==='waiting_for_user'?'Wacht op gebruiker':'Open'}
function splitValues(value){return value.split(/[\n,]/).map((v)=>v.trim()).filter(Boolean)}

async function boot(){const{data:{session}}=await supabase.auth.getSession();if(!session)return showLogin();await authorize(session.user)}
async function authorize(user){state.user=user;const{data:profile,error}=await supabase.from('profiles').select('id,display_name,email,role').eq('id',user.id).single();if(error||!['admin','support'].includes(profile?.role)){await supabase.auth.signOut();return showDenied()}state.profile=profile;$('#admin-name').textContent=profile.display_name||roleLabel(profile.role);$('#admin-email').textContent=profile.email||user.email;$('#admin-role').textContent=roleLabel(profile.role);$('#login-view').classList.add('hidden');$('#denied-view').classList.add('hidden');$('#app-view').classList.remove('hidden');applyPermissions();try{await supabase.rpc('touch_last_seen')}catch(error){console.warn('[PasKluis Beheer] Laatste activiteit kon niet worden bijgewerkt.',error)}await refreshAll()}
function showLogin(){$('#login-view').classList.remove('hidden');$('#app-view').classList.add('hidden');$('#denied-view').classList.add('hidden')}
function showDenied(){$('#denied-view').classList.remove('hidden');$('#login-view').classList.add('hidden');$('#app-view').classList.add('hidden')}
function applyPermissions(){const admin=state.profile.role==='admin';$$('.admin-nav,.admin-only').forEach((n)=>n.classList.toggle('hidden',!admin));const pages=admin?[['dashboard','Overzicht'],['users','Gebruikers & Plus'],['team','Medewerkers'],['support','Klantenservice'],['brands','Winkels & herkenning'],['faqs','Hulp & FAQ'],['settings','App-instellingen'],['activity','Activiteitenlog']]:[['dashboard','Overzicht'],['support','Klantenservice']];$('#mobile-nav').innerHTML=pages.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}

async function loadSource(name,primary,fallback=null){let result=await primary();if(result.error&&fallback)result=await fallback();if(result.error){console.error(`[PasKluis Beheer] ${name}:`,result.error);state.loadErrors.push(`${name}: ${result.error.message}`);return[]}return result.data||[]}
async function refreshAll(){state.loadErrors=[];const[profiles,entitlements,threads,brands,settings,faqs,audit]=await Promise.all([
  loadSource('Gebruikers',()=>supabase.from('profiles').select('id,display_name,email,role,created_at,updated_at,last_seen_at').order('created_at',{ascending:false}),()=>supabase.from('profiles').select('id,display_name,email,role,created_at,updated_at').order('created_at',{ascending:false})),
  loadSource('Plus-toegang',()=>supabase.from('entitlements').select('*').order('created_at',{ascending:false})),
  loadSource('Klantenservice',()=>supabase.from('support_threads').select('*').order('updated_at',{ascending:false}),()=>supabase.from('support_threads').select('id,user_id,subject,status,assigned_to,created_at,updated_at').order('updated_at',{ascending:false})),
  loadSource('Winkels',()=>supabase.from('brands').select('*').order('sort_order').order('name'),()=>supabase.from('brands').select('id,slug,name,logo_path,brand_color,supports_loyalty_card,supports_gift_card,is_active,sort_order,created_at,updated_at').order('sort_order').order('name')),
  loadSource('App-instellingen',()=>supabase.from('app_settings').select('*').order('category').order('sort_order').order('label'),()=>supabase.from('app_settings').select('*').order('category').order('label')),
  loadSource('Hulp en FAQ',()=>supabase.from('help_faqs').select('*').order('sort_order').order('question')),
  loadSource('Activiteitenlog',()=>supabase.from('admin_audit_log').select('*').order('created_at',{ascending:false}).limit(150))
]);state.profiles=profiles;state.entitlements=entitlements;state.threads=threads;state.brands=brands;state.settings=settings;state.faqs=faqs;state.audit=audit;await loadSupportExtras();renderAll();renderLoadStatus();if(state.loadErrors.length)toast(`${state.loadErrors.length} onderdeel${state.loadErrors.length===1?'':'en'} kon${state.loadErrors.length===1?'':'den'} niet laden.`)}
function renderLoadStatus(){const box=$('#load-status');if(!box)return;if(!state.loadErrors.length){box.classList.add('hidden');box.innerHTML='';return}box.classList.remove('hidden');box.innerHTML=`<strong>Niet alle gegevens konden worden geladen</strong><span>${state.loadErrors.map(escapeHtml).join('<br>')}</span><button class="secondary small-button refresh-all-inline">Opnieuw proberen</button>`;box.querySelector('.refresh-all-inline').addEventListener('click',refreshAll)}
function renderAll(){renderStats();renderUsers();renderTeam();renderThreads();renderBrands();renderFaqs();renderSettings();renderActivity()}

function renderStats(){const plusCount=state.profiles.filter((p)=>activeEntitlement(p.id)).length;const open=state.threads.filter((t)=>t.status!=='closed').length;const weekAgo=Date.now()-7*86400000;const newUsers=state.profiles.filter((p)=>new Date(p.created_at).getTime()>=weekAgo).length;const urgent=state.threads.filter((t)=>t.status!=='closed'&&['high','urgent'].includes(t.priority)).length;const staff=state.profiles.filter((p)=>p.role!=='user').length;$('#stat-users').textContent=state.profiles.length;$('#stat-new-users').textContent=`${newUsers} nieuw deze week`;$('#stat-plus').textContent=plusCount;$('#stat-plus-share').textContent=state.profiles.length?`${Math.round(plusCount/state.profiles.length*100)}% van gebruikers`:'0% van gebruikers';$('#stat-support').textContent=open;$('#stat-urgent').textContent=`${urgent} met hoge prioriteit`;$('#stat-brands').textContent=state.brands.filter((b)=>b.is_active).length;$('#stat-staff').textContent=`${staff} medewerkers`;$('#open-count').textContent=open;const actions=[];if(open)actions.push([`${open} klantvragen openstaand`,'Open klantenservice','support']);if(urgent)actions.push([`${urgent} vragen hebben hoge prioriteit`,'Direct bekijken','support']);const noRecognition=state.brands.filter((b)=>!(b.aliases?.length||b.recognition_keywords?.length||b.barcode_prefixes?.length)).length;if(noRecognition&&state.profile.role==='admin')actions.push([`${noRecognition} winkels zonder herkenningsregels`,'Winkels bekijken','brands']);if(!actions.length)actions.push(['Alles is bijgewerkt','Er zijn momenteel geen openstaande acties','dashboard']);$('#attention-list').innerHTML=actions.map(([title,copy,page])=>`<button class="action-item" data-go="${page}"><div><strong>${escapeHtml(title)}</strong><small>${escapeHtml(copy)}</small></div><span>›</span></button>`).join('');$('#recent-activity').innerHTML=activityMarkup(state.audit.slice(0,6))}

function filteredUsers(){const q=$('#user-search').value.trim().toLowerCase();const filter=$('#user-filter').value;return state.profiles.filter((p)=>p.role==='user'&&`${p.display_name||''} ${p.email||''}`.toLowerCase().includes(q)&&(filter==='all'||(filter==='plus'&&activeEntitlement(p.id))||(filter==='free'&&!activeEntitlement(p.id))))}
function renderUsers(){if(!$('#users-body'))return;const rows=filteredUsers();$('#users-body').innerHTML=rows.map((p)=>{const plus=activeEntitlement(p.id);return `<tr><td><div class="user-cell"><strong>${escapeHtml(p.display_name||'Naamloos account')}</strong><span>${escapeHtml(p.email||p.id)}</span></div></td><td>${formatDate(p.created_at,false)}</td><td><span class="pill">Gebruiker</span></td><td><span class="pill ${plus?'active':''}">${plus?`Plus · ${escapeHtml(plus.source)}`:'Gratis'}</span></td><td><button class="secondary small-button" data-view-user="${p.id}">Bekijken</button></td></tr>`}).join('')||'<tr><td colspan="5" class="empty-text">Geen gebruikers gevonden.</td></tr>'}
function openUser(id){const p=profileFor(id);if(!p)return;const plus=activeEntitlement(id);$('#user-detail').innerHTML=`<div class="dialog-title"><div><h2>${escapeHtml(p.display_name||'Naamloos account')}</h2><p>${escapeHtml(p.email||p.id)}</p></div><button class="icon-button dialog-close" aria-label="Sluiten">×</button></div><div class="detail-grid"><div class="detail-box"><span>Account</span><strong>${roleLabel(p.role)}</strong></div><div class="detail-box"><span>Aangemaakt</span><strong>${formatDate(p.created_at,false)}</strong></div><div class="detail-box"><span>Laatste activiteit</span><strong>${formatDate(p.last_seen_at)}</strong></div><div class="detail-box"><span>Toegang</span><strong>${plus?'PasKluis Plus':'Gratis'}</strong></div></div>${plus?`<div class="detail-box"><span>Plus-bron</span><strong>${escapeHtml(plus.source)}</strong><small>${plus.expires_at?`Tot ${formatDate(plus.expires_at,false)}`:'Geen einddatum'}</small></div>`:''}<div class="detail-actions"><button class="${plus?'secondary':'primary'}" data-plus-user="${p.id}" data-plus-action="${plus?'revoke':'grant'}">${plus?'Plus intrekken':'Gratis Plus geven'}</button></div>`;$('#user-dialog').showModal()}
async function changePlus(userId,action){if(state.profile.role!=='admin')return;const ok=await confirmAction(action==='grant'?'Gratis Plus geven?':'Plus intrekken?',action==='grant'?'Deze gebruiker krijgt Plus zonder betaling.':'De handmatig toegekende Plus-toegang wordt beëindigd.');if(!ok)return;if(action==='grant'){const{error}=await supabase.from('entitlements').insert({user_id:userId,product_id:'paskluis_plus',source:'complimentary',created_by:state.user.id,note:'Toegekend via PasKluis Beheer'});if(error)return toast(error.message.includes('duplicate')?'Plus is al actief.':'Plus kon niet worden toegekend.')}else{const{error}=await supabase.from('entitlements').update({revoked_at:new Date().toISOString()}).eq('user_id',userId).eq('product_id','paskluis_plus').is('revoked_at',null);if(error)return toast('Plus kon niet worden ingetrokken.')}$('#user-dialog').close();toast(action==='grant'?'Plus is toegekend.':'Plus is ingetrokken.');await refreshAll()}

function renderTeam(){if(!$('#team-grid'))return;const staff=state.profiles.filter((p)=>p.role!=='user');$('#team-grid').innerHTML=staff.map((p)=>`<article class="team-card"><div class="team-card-head"><div class="avatar">${escapeHtml((p.display_name||p.email||'?').charAt(0).toUpperCase())}</div><div class="team-card-info"><strong>${escapeHtml(p.display_name||'Naamloos')}</strong><span>${escapeHtml(p.email||p.id)}</span></div></div><label>Rol<select data-staff-role="${escapeHtml(p.email||'')}" ${p.id===state.user.id?'disabled':''}><option value="support" ${p.role==='support'?'selected':''}>Klantenservice</option><option value="admin" ${p.role==='admin'?'selected':''}>Beheerder</option></select></label><div class="team-card-actions"><span class="pill ${p.role==='admin'?'active':''}">${roleLabel(p.role)}</span>${p.id!==state.user.id?`<button class="text-button" data-remove-staff="${escapeHtml(p.email||'')}">Toegang verwijderen</button>`:''}</div></article>`).join('')||'<div class="empty-text">Nog geen medewerkers.</div>'}
function updateRoleExplanation(){const admin=$('#staff-role').value==='admin';$('#staff-role-explanation').innerHTML=`<strong>${admin?'Beheerder':'Klantenservice'}</strong><span>${admin?'Volledige toegang tot gebruikers, medewerkers, winkels, instellingen en klantenservice.':'Toegang tot het overzicht en klantgesprekken, zonder kritieke beheerinstellingen.'}</span>`}
async function setStaffRole(email,role){const{error}=await supabase.rpc('set_staff_role_by_email',{p_email:email,p_role:role});if(error){toast(error.message);await refreshAll();return false}toast(role==='user'?'Medewerkerstoegang verwijderd.':'Rol aangepast.');await refreshAll();return true}
async function getFunctionErrorMessage(error,data){if(data?.error)return data.error;if(!error)return'';try{const response=error.context?.clone?.()||error.context;if(response?.json){const payload=await response.json();if(payload?.error||payload?.message)return payload.error||payload.message}}catch{}return error.message||'Uitnodigen is niet gelukt.'}
async function inviteStaff(){const email=$('#staff-email').value.trim();const role=$('#staff-role').value;const displayName=$('#staff-name').value.trim();$('#staff-error').textContent='';const{data,error}=await supabase.functions.invoke('invite-staff',{body:{email,role,displayName,redirectTo:new URL('.',location.href).href}});if(error||data?.error){const message=await getFunctionErrorMessage(error,data);const fallback=await supabase.rpc('set_staff_role_by_email',{p_email:email,p_role:role});if(fallback.error){$('#staff-error').textContent=message||fallback.error.message||'Uitnodigen is niet gelukt.';return}}$('#staff-dialog').close();$('#staff-form').reset();toast(data?.existing?'Bestaand account heeft toegang gekregen.':'Uitnodiging is verstuurd.');await refreshAll()}

function overdue(t){return t.status==='open'&&t.response_due_at&&new Date(t.response_due_at).getTime()<Date.now()}
function filteredThreads(){const filter=$('#support-filter').value;const q=$('#support-search').value.trim().toLowerCase();return state.threads.filter(t=>(filter==='all'||(filter==='active'&&t.status!=='closed')||(filter==='overdue'&&overdue(t))||(filter==='mine'&&t.assigned_to===state.user.id&&t.status!=='closed')||t.status===filter)&&`${t.subject} ${supportName(t)} ${t.category}`.toLowerCase().includes(q)).sort((a,b)=>Number(overdue(b))-Number(overdue(a))||new Date(b.updated_at)-new Date(a.updated_at))}

function supportName(t){const user=profileFor(t.user_id);return user?.display_name||user?.email||t.guest_name||t.guest_email||'Gast'}
function renderThreads(){const items=filteredThreads();$('#thread-list').innerHTML=items.map((t)=>`<button class="thread-item ${state.selectedThread?.id===t.id?'active':''}" data-thread="${t.id}"><strong>${escapeHtml(t.subject)}</strong><span>${escapeHtml(supportName(t))} · ${formatDate(t.updated_at)}</span><div class="thread-meta"><span class="pill ${t.status==='open'?'open':t.status==='waiting_for_user'?'waiting':'closed'}">${statusLabel(t.status)}</span>${overdue(t)?'<span class="pill urgent">Langer dan 12 uur</span>':''}${t.assigned_to?`<span class="pill">${escapeHtml(profileFor(t.assigned_to)?.display_name||'Toegewezen')}</span>`:''}${!t.user_id?'<span class="pill">Zonder account</span>':''}${['high','urgent'].includes(t.priority)?`<span class="pill ${t.priority}">${t.priority==='urgent'?'Urgent':'Hoog'}</span>`:''}</div></button>`).join('')||'<div class="empty-text">Geen gesprekken in dit filter.</div>'}
async function openThread(id){state.selectedThread=state.threads.find((t)=>t.id===id);renderThreads();const{data,error}=await supabase.from('support_messages').select('*').eq('thread_id',id).order('created_at');if(state.selectedThread?.id!==id)return;if(error)return toast('Berichten konden niet worden geladen.');state.messages=data||[];const t=state.selectedThread;$('#conversation-empty').classList.add('hidden');$('#conversation').classList.remove('hidden');$('#conversation-subject').textContent=t.subject;$('#conversation-user').textContent=t.guest_email?`${t.guest_name||'Gast'} · ${t.guest_email}`:(profileFor(t.user_id)?.email||profileFor(t.user_id)?.display_name||t.user_id);$('#toggle-thread-status').textContent=t.status==='closed'?'Heropenen':'Sluiten';$('#reply-form').classList.toggle('hidden',t.status==='closed');$('#thread-category').value=t.category||'overig';$('#thread-priority').value=t.priority||'normal';const privateResult=await supabase.from('support_private_notes').select('note').eq('thread_id',id).maybeSingle();if(state.selectedThread?.id!==id)return;$('#thread-note').value=privateResult.data?.note||'';$('#thread-note').disabled=!!privateResult.error;$('#thread-assignee').innerHTML='<option value="">Nog niet toegewezen</option>'+state.profiles.filter(p=>p.role!=='user').map(p=>`<option value="${p.id}" ${t.assigned_to===p.id?'selected':''}>${escapeHtml(p.display_name||p.email)}</option>`).join('');$('#thread-context').textContent=`${t.locale==='en'?'Engels':'Nederlands'} · ${t.category||'overig'} · ${t.client_context?.platform||'Platform onbekend'} ${t.client_context?.version||''}`;$('#canned-reply').innerHTML='<option value="">Antwoordvoorbeeld kiezen</option>'+state.canned.map(r=>`<option value="${r.id}">${escapeHtml(r.title)}</option>`).join('');const list=$('#message-list');list.innerHTML=state.messages.map((m)=>`<div class="message ${m.sender_id===state.user.id?'mine':''}">${m.sender_kind==='automatic'?'<strong>Automatische ontvangstbevestiging</strong><br>':''}${escapeHtml(m.message)}<small>${formatDate(m.created_at)}</small></div>`).join('');list.scrollTop=list.scrollHeight;await loadSupportAttachments(id)}

function renderFaqs(){const body=$('#faqs-body');if(!body)return;body.innerHTML=state.faqs.map((f)=>`<tr><td><div class="user-cell"><strong>${escapeHtml(f.question)}</strong><span>${escapeHtml(f.answer)}</span></div></td><td><span class="pill">${escapeHtml(f.category)}</span></td><td>${f.sort_order??0}</td><td><span class="pill ${f.is_active?'active':''}">${f.is_active?'Zichtbaar':'Verborgen'}</span><br><span class="pill">${f.question_en?.trim()&&f.answer_en?.trim()?'NL + EN':'NL · Engelse vertaling ontbreekt'}</span></td><td><button class="secondary small-button" data-edit-faq="${f.id}">Bewerken</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty-text">Nog geen veelgestelde vragen.</td></tr>'}
function openFaqDialog(faq=null){$('#faq-id').value=faq?.id||'';$('#faq-form-title').textContent=faq?'Vraag bewerken':'Nieuwe vraag';$('#faq-category').value=faq?.category||'Algemeen';$('#faq-question').value=faq?.question||'';$('#faq-answer').value=faq?.answer||'';$('#faq-category-en').value=faq?.category_en||'';$('#faq-question-en').value=faq?.question_en||'';$('#faq-answer-en').value=faq?.answer_en||'';$('#faq-order').value=faq?.sort_order??0;$('#faq-active').checked=faq?.is_active??true;$('#faq-error').textContent='';$('#faq-dialog').showModal()}
async function saveFaq(){const id=$('#faq-id').value;const payload={category:$('#faq-category').value.trim(),question:$('#faq-question').value.trim(),answer:$('#faq-answer').value.trim(),category_en:$('#faq-category-en').value.trim(),question_en:$('#faq-question-en').value.trim(),answer_en:$('#faq-answer-en').value.trim(),sort_order:Number($('#faq-order').value)||0,is_active:$('#faq-active').checked,updated_at:new Date().toISOString()};if(Boolean(payload.question_en)!==Boolean(payload.answer_en))return $('#faq-error').textContent='Vul de Engelse vraag én het antwoord in, of laat beide leeg.';if(payload.question_en&&!payload.category_en)payload.category_en='General';const result=id?await supabase.from('help_faqs').update(payload).eq('id',id):await supabase.from('help_faqs').insert(payload);if(result.error)return $('#faq-error').textContent=result.error.message;$('#faq-dialog').close();toast('Veelgestelde vraag opgeslagen.');await refreshAll()}
async function saveThreadMeta(){if(!state.selectedThread)return;const id=state.selectedThread.id;const{error}=await supabase.from('support_threads').update({category:$('#thread-category').value,priority:$('#thread-priority').value,assigned_to:$('#thread-assignee').value||null}).eq('id',id);if(error)return toast('Gegevens konden niet worden opgeslagen.');if(!$('#thread-note').disabled){const note=await supabase.from('support_private_notes').upsert({thread_id:id,note:$('#thread-note').value.trim(),updated_by:state.user.id,updated_at:new Date().toISOString()});if(note.error)return toast('Interne notitie kon niet worden opgeslagen.');}toast('Gespreksgegevens opgeslagen.');await refreshAll();await openThread(id)}

async function sendReply(text){const thread=state.selectedThread;if(!thread)return;const{error}=await supabase.from('support_messages').insert({thread_id:thread.id,sender_id:state.user.id,sender_kind:'staff',message:text});if(error)return toast('Antwoord kon niet worden verzonden.');$('#reply-message').value='';await refreshAll();await openThread(thread.id);toast('Antwoord verzonden.')}
async function toggleThreadStatus(){const thread=state.selectedThread;if(!thread)return;const next=thread.status==='closed'?'open':'closed';const{error}=await supabase.from('support_threads').update({status:next,updated_at:new Date().toISOString()}).eq('id',thread.id);if(error)return toast('Status kon niet worden aangepast.');await refreshAll();await openThread(thread.id)}

function renderBrands(){const q=$('#brand-search').value.trim().toLowerCase();const brands=state.brands.filter((b)=>`${b.name} ${b.slug} ${(b.aliases||[]).join(' ')}`.toLowerCase().includes(q));$('#brands-body').innerHTML=brands.map((b)=>{const count=(b.aliases?.length||0)+(b.recognition_keywords?.length||0)+(b.barcode_prefixes?.length||0);return `<tr><td><div class="user-cell"><strong>${escapeHtml(b.name)}</strong><span>${escapeHtml(b.slug)}</span></div></td><td>${b.supports_loyalty_card?'Klantenkaart':''}${b.supports_loyalty_card&&b.supports_gift_card?' · ':''}${b.supports_gift_card?'Cadeaukaart':''}</td><td><span class="pill ${b.is_featured?'active':''}">${b.is_featured?'Populair':'Nee'}</span></td><td><span class="pill ${count?'active':''}">${count?`${count} regels`:'Nog leeg'}</span></td><td>${b.sort_order??0}</td><td><span class="pill ${b.is_active?'active':''}">${b.is_active?'Actief':'Verborgen'}</span></td><td><button class="secondary small-button" data-edit-brand="${b.id}">Bewerken</button></td></tr>`}).join('')||'<tr><td colspan="7" class="empty-text">Geen winkels gevonden.</td></tr>'}
function renderLogoPreview(source=''){const src=source.startsWith('assets/')?`../${source}`:source;$('#brand-logo-preview').innerHTML=src?`<img src="${escapeHtml(src)}" alt="Logo voorbeeld" onerror="this.parentElement.innerHTML='<span>Voorbeeld kon niet worden geladen</span>'"/>`:'<span>Nog geen logo gekozen</span>'}
function openBrandDialog(brand=null){$('#brand-form-title').textContent=brand?'Winkel bewerken':'Nieuwe winkel';$('#brand-id').value=brand?.id||'';$('#brand-name').value=brand?.name||'';$('#brand-slug').value=brand?.slug||'';$('#brand-logo').value=brand?.logo_path||'';$('#brand-logo-file').value='';$('#brand-color').value=brand?.brand_color||'#D51B46';$('#brand-order').value=brand?.sort_order??0;$('#brand-aliases').value=(brand?.aliases||[]).join('\n');$('#brand-keywords').value=(brand?.recognition_keywords||[]).join('\n');$('#brand-prefixes').value=(brand?.barcode_prefixes||[]).join(', ');$('#brand-loyalty').checked=brand?.supports_loyalty_card??true;$('#brand-gift').checked=brand?.supports_gift_card??false;$('#brand-featured').checked=brand?.is_featured??false;$('#brand-active').checked=brand?.is_active??true;$('#brand-error').textContent='';renderLogoPreview(brand?.logo_path||'');$('#brand-dialog').showModal()}
async function uploadBrandLogo(slug){const file=$('#brand-logo-file').files[0];if(!file)return $('#brand-logo').value.trim()||null;if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('Gebruik een PNG-, JPG- of WebP-logo.');if(file.size>2097152)throw new Error('Het logo is groter dan 2 MB.');const extension=(file.name.split('.').pop()||'png').toLowerCase();const path=`${slug}/${Date.now()}.${extension}`;const{error}=await supabase.storage.from('brand-logos').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return supabase.storage.from('brand-logos').getPublicUrl(path).data.publicUrl}
async function saveBrand(){const id=$('#brand-id').value;const slug=$('#brand-slug').value.trim();try{const logoPath=await uploadBrandLogo(slug);if(/\.svg(?:$|[?#])/i.test(logoPath))throw new Error('Gebruik een PNG-, JPG- of WebP-bestand. SVG wordt niet ondersteund in de app.');const payload={name:$('#brand-name').value.trim(),slug,logo_path:logoPath,brand_color:$('#brand-color').value,sort_order:Number($('#brand-order').value)||0,aliases:splitValues($('#brand-aliases').value),recognition_keywords:splitValues($('#brand-keywords').value),barcode_prefixes:splitValues($('#brand-prefixes').value),supports_loyalty_card:$('#brand-loyalty').checked,supports_gift_card:$('#brand-gift').checked,is_featured:$('#brand-featured').checked,is_active:$('#brand-active').checked,updated_at:new Date().toISOString()};const result=id?await supabase.from('brands').update(payload).eq('id',id):await supabase.from('brands').insert(payload);if(result.error)throw result.error;$('#brand-dialog').close();toast('Winkel opgeslagen. Logo-afstelling blijft in de app.');await refreshAll()}catch(error){$('#brand-error').textContent=error.message||'Opslaan is niet gelukt.'}}

const settingCategory={features:'Functies',defaults:'Standaardinstellingen',plus:'Plus & toegang',content:'Hulp, privacy & teksten',home:'Home & locatie',app:'App & onderhoud',versions:'Appversies',general:'Algemeen'};
function settingInput(s){const value=s.value;const type=s.input_type||'auto';const key=escapeHtml(s.key);if(type==='switch'||(type==='auto'&&typeof value==='boolean'))return `<label class="admin-switch"><input class="toggle-input" data-setting="${key}" type="checkbox" ${value?'checked':''}/><span>${value?'Aan':'Uit'}</span></label>`;if(type==='select'&&Array.isArray(s.options)){return `<select data-setting="${key}" data-value-type="${typeof value}">${s.options.map((option)=>{const optionValue=option?.value??option;const optionLabel=option?.label??optionValue;return `<option value="${escapeHtml(optionValue)}" ${String(optionValue)===String(value)?'selected':''}>${escapeHtml(optionLabel)}</option>`}).join('')}</select>`}if(type==='textarea')return `<textarea data-setting="${key}" rows="4">${escapeHtml(value??'')}</textarea>`;if(type==='number'||(type==='auto'&&typeof value==='number'))return `<input data-setting="${key}" type="number" value="${escapeHtml(value)}"/>`;return `<input data-setting="${key}" value="${escapeHtml(value??'')}"/>`}
function renderSettings(){const visible=state.settings.filter((s)=>s.is_visible!==false);const groups=Object.groupBy?Object.groupBy(visible,(s)=>s.category):visible.reduce((a,s)=>((a[s.category]??=[]).push(s),a),{});$('#settings-grid').innerHTML=Object.entries(groups).map(([category,items])=>`<section class="setting-group"><div class="setting-group-head"><h2>${escapeHtml(settingCategory[category]||category)}</h2><span>${items.length} instellingen</span></div>${items.map((s)=>`<div class="setting-row"><div class="setting-copy"><div><strong>${escapeHtml(s.label)}</strong>${s.plus_only?'<span class="pill active">Plus</span>':''}${s.platform&&s.platform!=='all'?`<span class="pill">${s.platform==='ios'?'iOS':'Android'}</span>`:''}</div><small>${escapeHtml(s.description||'')}</small></div>${settingInput(s)}</div>`).join('')}</section>`).join('')||'<div class="empty-text">Voer de nieuwste Supabase-migratie uit om app-instellingen te beheren.</div>';$$('.admin-switch input').forEach((input)=>input.addEventListener('change',()=>{input.nextElementSibling.textContent=input.checked?'Aan':'Uit'}))}
async function saveSettings(){const changes=$$('[data-setting]').map((input)=>{const original=state.settings.find((s)=>s.key===input.dataset.setting);let value=input.type==='checkbox'?input.checked:input.type==='number'||input.dataset.valueType==='number'?Number(input.value):input.value;return{...original,value,updated_by:state.user.id,updated_at:new Date().toISOString()}});for(const item of changes){const{error}=await supabase.from('app_settings').update({value:item.value,updated_by:item.updated_by,updated_at:item.updated_at}).eq('key',item.key);if(error)return toast(`Instelling ${item.label} kon niet worden opgeslagen.`)}toast('App-instellingen opgeslagen. De nieuwe waarden gelden direct als standaard voor de app.');await refreshAll()}

function auditTitle(item){const names={profiles:'Medewerker',entitlements:'Plus-toegang',brands:'Winkel',app_settings:'App-instelling',help_faqs:'Veelgestelde vraag',support_threads:'Klantenservice'};const verb={insert:'toegevoegd',update:'gewijzigd',delete:'verwijderd'};return `${names[item.entity_type]||item.entity_type} ${verb[item.action]||item.action}`}
function activityMarkup(items){return items.map((item)=>{const actor=profileFor(item.actor_id);return `<div class="timeline-item"><span class="timeline-dot"></span><div class="timeline-copy"><strong>${escapeHtml(auditTitle(item))}</strong><span>${escapeHtml(actor?.display_name||actor?.email||'Systeem')}</span></div><time>${formatDate(item.created_at)}</time></div>`}).join('')||'<div class="empty-text">Nog geen wijzigingen geregistreerd.</div>'}
function renderActivity(){if(!$('#activity-list'))return;const filter=$('#activity-filter').value;$('#activity-list').innerHTML=activityMarkup(state.audit.filter((a)=>filter==='all'||a.entity_type===filter))}

function showPage(page){if(state.profile.role!=='admin'&&!['dashboard','support'].includes(page))page='dashboard';$$('.page').forEach((n)=>n.classList.remove('active-page'));$$('.nav-button').forEach((n)=>n.classList.toggle('active',n.dataset.page===page));$(`#page-${page}`).classList.add('active-page');$('#mobile-nav').value=page}
function confirmAction(title,message){return new Promise((resolve)=>{const d=$('#confirm-dialog');$('#confirm-title').textContent=title;$('#confirm-message').textContent=message;const done=()=>{d.removeEventListener('close',done);resolve(d.returnValue==='confirm')};d.addEventListener('close',done);d.showModal()})}

$('#login-form').addEventListener('submit',async(e)=>{e.preventDefault();$('#login-error').textContent='';const{data,error}=await supabase.auth.signInWithPassword({email:$('#login-email').value.trim(),password:$('#login-password').value});if(error)return $('#login-error').textContent='E-mailadres of wachtwoord klopt niet.';await authorize(data.user)});$('#logout-button').addEventListener('click',async()=>{await supabase.auth.signOut();location.reload()});$('#denied-logout').addEventListener('click',async()=>{await supabase.auth.signOut();location.reload()});
$$('.nav-button').forEach((b)=>b.addEventListener('click',()=>showPage(b.dataset.page)));$('#mobile-nav').addEventListener('change',(e)=>showPage(e.target.value));document.addEventListener('click',(e)=>{const go=e.target.closest('[data-go]');if(go)showPage(go.dataset.go);const close=e.target.closest('.dialog-close');if(close)close.closest('dialog').close()});$$('.refresh-all').forEach((b)=>b.addEventListener('click',refreshAll));
$('#user-search').addEventListener('input',renderUsers);$('#user-filter').addEventListener('change',renderUsers);$('#users-body').addEventListener('click',(e)=>{const b=e.target.closest('[data-view-user]');if(b)openUser(b.dataset.viewUser)});$('#user-detail').addEventListener('click',(e)=>{const b=e.target.closest('[data-plus-user]');if(b)changePlus(b.dataset.plusUser,b.dataset.plusAction)});
$('#new-staff').addEventListener('click',()=>{$('#staff-form').reset();$('#staff-error').textContent='';updateRoleExplanation();$('#staff-dialog').showModal()});$('#staff-role').addEventListener('change',updateRoleExplanation);$('#staff-form').addEventListener('submit',(e)=>{e.preventDefault();inviteStaff()});$('#team-grid').addEventListener('change',async(e)=>{const select=e.target.closest('[data-staff-role]');if(!select)return;const ok=await confirmAction('Rol aanpassen?',`${select.dataset.staffRole} wordt ${roleLabel(select.value).toLowerCase()}.`);if(ok)await setStaffRole(select.dataset.staffRole,select.value);else renderTeam()});$('#team-grid').addEventListener('click',async(e)=>{const b=e.target.closest('[data-remove-staff]');if(!b)return;const ok=await confirmAction('Medewerkerstoegang verwijderen?',`${b.dataset.removeStaff} wordt weer een normaal gebruikersaccount.`);if(ok)await setStaffRole(b.dataset.removeStaff,'user')});
$('#support-filter').addEventListener('change',renderThreads);$('#refresh-support').addEventListener('click',refreshAll);$('#thread-list').addEventListener('click',(e)=>{const b=e.target.closest('[data-thread]');if(b)openThread(b.dataset.thread)});$('#save-thread-meta').addEventListener('click',saveThreadMeta);$('#reply-form').addEventListener('submit',(e)=>{e.preventDefault();const text=$('#reply-message').value.trim();if(text)sendReply(text)});$('#toggle-thread-status').addEventListener('click',toggleThreadStatus);
$('#brand-search').addEventListener('input',renderBrands);$('#new-brand').addEventListener('click',()=>openBrandDialog());$('#brands-body').addEventListener('click',(e)=>{const b=e.target.closest('[data-edit-brand]');if(b)openBrandDialog(state.brands.find((x)=>x.id===b.dataset.editBrand))});$('#cancel-brand').addEventListener('click',()=>$('#brand-dialog').close());$('#brand-form').addEventListener('submit',(e)=>{e.preventDefault();saveBrand()});$('#brand-logo-file').addEventListener('change',(e)=>{const file=e.target.files[0];if(file)renderLogoPreview(URL.createObjectURL(file))});$('#brand-logo').addEventListener('input',(e)=>renderLogoPreview(e.target.value.trim()));
$('#new-faq').addEventListener('click',()=>openFaqDialog());$('#faqs-body').addEventListener('click',(e)=>{const b=e.target.closest('[data-edit-faq]');if(b)openFaqDialog(state.faqs.find((x)=>x.id===b.dataset.editFaq))});$('#faq-form').addEventListener('submit',(e)=>{e.preventDefault();saveFaq()});
$('#save-settings').addEventListener('click',saveSettings);$('#activity-filter').addEventListener('change',renderActivity);$('#refresh-activity').addEventListener('click',refreshAll);
boot();

async function loadSupportExtras(){const results=await Promise.all([supabase.from('support_canned_replies').select('*').eq('active',true).order('title'),supabase.from('service_incidents').select('*').order('updated_at',{ascending:false}),supabase.from('notification_outbox').select('id,event_type,attempts,last_error,delivered_at').is('delivered_at',null).order('created_at',{ascending:false}).limit(50)]);state.canned=results[0].data||[];state.incidents=results[1].data||[];state.deliveries=results[2].data||[];const failed=state.deliveries.filter(d=>d.attempts>=8);$('#support-delivery-status').textContent=results[2].error?'Verzendstatus niet beschikbaar. Controleer de verbinding en serverconfiguratie.':failed.length?`Minstens ${failed.length} meldingen vereisen aandacht. Controleer de mail- en pushkoppeling.`:state.deliveries.length?'Er staan meldingen klaar voor verzending.':'Geen vastgelopen meldingen.';$('#retry-notifications').classList.toggle('hidden',!!results[2].error||failed.length===0);$('#incident-list').innerHTML=state.incidents.map(i=>`<div class="action-item"><div><strong>${escapeHtml(i.title_nl)}</strong><small>${escapeHtml(i.body_nl)}</small></div><button class="secondary small-button" data-resolve-incident="${i.id}">${i.active?'Oplossen':'Verwijderen'}</button></div>`).join('')||'<p>Geen bekende storingen.</p>';$('#canned-list').innerHTML=state.canned.map(r=>`<div class="action-item"><div><strong>${escapeHtml(r.title)}</strong><small>${escapeHtml(r.body_nl)}</small></div><button class="secondary small-button" data-remove-canned="${r.id}">Verwijderen</button></div>`).join('')}
$('#support-search').addEventListener('input',renderThreads);
$('#canned-reply').addEventListener('change',()=>{const r=state.canned.find(r=>r.id===$('#canned-reply').value);if(r)$('#reply-message').value=state.selectedThread?.locale==='en'?(r.body_en||r.body_nl):r.body_nl;});
$('#new-canned').addEventListener('click',()=>$('#canned-dialog').showModal());
$('#new-incident').addEventListener('click',()=>$('#incident-dialog').showModal());
$('#canned-form').addEventListener('submit',async e=>{e.preventDefault();const{error}=await supabase.from('support_canned_replies').insert({title:$('#canned-title').value.trim(),body_nl:$('#canned-nl').value.trim(),body_en:$('#canned-en').value.trim()});if(error)return toast('Opslaan is niet gelukt.');$('#canned-dialog').close();e.target.reset();await loadSupportExtras();});
$('#incident-form').addEventListener('submit',async e=>{e.preventDefault();const{error}=await supabase.from('service_incidents').insert({title_nl:$('#incident-title-nl').value.trim(),title_en:$('#incident-title-en').value.trim(),body_nl:$('#incident-body-nl').value.trim(),body_en:$('#incident-body-en').value.trim()});if(error)return toast('Opslaan is niet gelukt.');$('#incident-dialog').close();e.target.reset();await loadSupportExtras();});
$('#incident-list').addEventListener('click',async e=>{const b=e.target.closest('[data-resolve-incident]');if(!b)return;const i=state.incidents.find(i=>i.id===b.dataset.resolveIncident);const result=i.active?await supabase.from('service_incidents').update({active:false,updated_at:new Date().toISOString()}).eq('id',i.id):await supabase.from('service_incidents').delete().eq('id',i.id);if(result.error)return toast('Aanpassen is niet gelukt.');await loadSupportExtras();});
$('#canned-list').addEventListener('click',async e=>{const b=e.target.closest('[data-remove-canned]');if(!b)return;const{error}=await supabase.from('support_canned_replies').update({active:false}).eq('id',b.dataset.removeCanned);if(error)return toast('Aanpassen is niet gelukt.');await loadSupportExtras();});

async function loadSupportAttachments(threadId){
 const {data,error}=await supabase.functions.invoke('support-attachments',{body:{action:'list',thread_id:threadId}});
 if(state.selectedThread?.id!==threadId)return;
 if(error){toast('Eventuele bijlagen konden niet worden geladen.');return;}
 const messages=[...document.querySelectorAll('#message-list .message')];
 for(const attachment of data?.attachments||[]){
  const index=state.messages.findIndex(m=>m.id===attachment.message_id);if(index<0||!messages[index])continue;
  const link=document.createElement('a');link.href=attachment.url;link.target='_blank';link.rel='noopener noreferrer';
  const image=document.createElement('img');image.src=attachment.url;image.alt='Bijgevoegde screenshot';image.loading='lazy';image.className='support-attachment';
  link.append(image);messages[index].append(link);
 }
}

$('#retry-notifications').addEventListener('click',async e=>{const button=e.currentTarget;button.disabled=true;try{const {data,error}=await supabase.rpc('retry_failed_notifications');if(error){toast('Opnieuw proberen is niet gelukt.');return;}toast(`${data||0} meldingen opnieuw klaargezet.`);await loadSupportExtras();}finally{button.disabled=false;}});
