-- One canonical shared card with separate access memberships. This prevents
-- divergent per-recipient copies when two Plus members edit the same card.
create table if not exists public.shared_cards (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  card_external_id text not null,
  card_type text not null check (card_type in ('Pasje', 'QR-code', 'QR-set', 'Cadeaukaart')),
  card_payload jsonb not null,
  version bigint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  deleted_at timestamptz,
  unique (owner_id, card_external_id)
);

create table if not exists public.card_share_members (
  id uuid primary key default gen_random_uuid(),
  shared_card_id uuid not null references public.shared_cards(id) on delete cascade,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  recipient_email text not null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz,
  removed_by_recipient_at timestamptz,
  unique (shared_card_id, recipient_id)
);

create table if not exists public.card_share_events (
  id bigint generated by default as identity primary key,
  shared_card_id uuid not null references public.shared_cards(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null check (action in ('shared', 'updated', 'revoked', 'removed')),
  version bigint,
  created_at timestamptz not null default now()
);

alter table public.shared_cards enable row level security;
alter table public.card_share_members enable row level security;
alter table public.card_share_events enable row level security;

create or replace function public.is_shared_card_owner(
  p_shared_card_id uuid,
  p_user_id uuid
) returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.shared_cards
    where id = p_shared_card_id and owner_id = p_user_id
  );
$$;

create or replace function public.is_active_shared_card_recipient(
  p_shared_card_id uuid,
  p_user_id uuid
) returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.card_share_members
    where shared_card_id = p_shared_card_id
      and recipient_id = p_user_id
      and revoked_at is null
      and removed_by_recipient_at is null
  );
$$;

create or replace function public.has_paskluis_plus(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.entitlements
    where user_id = p_user_id
      and product_id = 'paskluis_plus'
      and revoked_at is null
      and (expires_at is null or expires_at > now())
  );
$$;

create policy "Owners and active recipients can read shared cards"
on public.shared_cards for select to authenticated
using (
  owner_id = auth.uid()
  or public.is_active_shared_card_recipient(id, auth.uid())
);

create policy "Owners and recipients can read memberships"
on public.card_share_members for select to authenticated
using (
  recipient_id = auth.uid()
  or public.is_shared_card_owner(shared_card_id, auth.uid())
);

create policy "Participants can read card share events"
on public.card_share_events for select to authenticated
using (
  public.is_shared_card_owner(shared_card_id, auth.uid())
  or public.is_active_shared_card_recipient(shared_card_id, auth.uid())
);

-- Preserve existing shared gift cards. The newest payload becomes canonical.
insert into public.shared_cards (
  owner_id, card_external_id, card_type, card_payload, created_at, updated_at, updated_by
)
select distinct on (owner_id, card_external_id)
  owner_id,
  card_external_id,
  'Cadeaukaart',
  card_payload,
  created_at,
  updated_at,
  owner_id
from public.gift_card_shares
order by owner_id, card_external_id, updated_at desc
on conflict (owner_id, card_external_id) do nothing;

insert into public.card_share_members (
  shared_card_id, recipient_id, recipient_email, created_at, revoked_at
)
select card.id, old.recipient_id, old.recipient_email, old.created_at, old.revoked_at
from public.gift_card_shares old
join public.shared_cards card
  on card.owner_id = old.owner_id
 and card.card_external_id = old.card_external_id
on conflict (shared_card_id, recipient_id) do update
set recipient_email = excluded.recipient_email,
    revoked_at = excluded.revoked_at;

create or replace function public.share_card_by_email(
  p_recipient_email text,
  p_card_external_id text,
  p_card_type text,
  p_card_payload jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_recipient uuid;
  v_card public.shared_cards;
  v_member uuid;
begin
  if auth.uid() is null then raise exception 'Je moet ingelogd zijn.'; end if;
  if not public.has_paskluis_plus(auth.uid()) then
    raise exception 'PasKluis Plus is vereist om kaarten te delen.';
  end if;
  if p_card_external_id is null or trim(p_card_external_id) = '' then
    raise exception 'Deze kaart heeft geen geldig kaartnummer.';
  end if;
  if p_card_type not in ('Pasje', 'QR-code', 'QR-set', 'Cadeaukaart') then
    raise exception 'Dit kaarttype kan niet worden gedeeld.';
  end if;

  select id into v_recipient
  from public.profiles
  where lower(email) = lower(trim(p_recipient_email))
  limit 1;
  if v_recipient is null then
    raise exception 'Geen PasKluis-account gevonden met dit e-mailadres.';
  end if;
  if v_recipient = auth.uid() then
    raise exception 'Je kunt een kaart niet met jezelf delen.';
  end if;

  insert into public.shared_cards (
    owner_id, card_external_id, card_type, card_payload, updated_by
  ) values (
    auth.uid(), p_card_external_id, p_card_type, p_card_payload, auth.uid()
  )
  on conflict (owner_id, card_external_id) do update
    set deleted_at = null
  returning * into v_card;

  insert into public.card_share_members (
    shared_card_id, recipient_id, recipient_email
  ) values (
    v_card.id, v_recipient, lower(trim(p_recipient_email))
  )
  on conflict (shared_card_id, recipient_id) do update
    set recipient_email = excluded.recipient_email,
        revoked_at = null,
        removed_by_recipient_at = null
  returning id into v_member;

  insert into public.card_share_events (shared_card_id, actor_id, action, version)
  values (v_card.id, auth.uid(), 'shared', v_card.version);

  return jsonb_build_object(
    'membership_id', v_member,
    'shared_card_id', v_card.id,
    'version', v_card.version,
    'recipient_can_edit', public.has_paskluis_plus(v_recipient)
  );
end;
$$;

create or replace function public.update_shared_card(
  p_shared_card_id uuid,
  p_expected_version bigint,
  p_card_payload jsonb
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_card public.shared_cards;
  v_next_version bigint;
begin
  if auth.uid() is null then raise exception 'Je moet ingelogd zijn.'; end if;

  select * into v_card
  from public.shared_cards
  where id = p_shared_card_id and deleted_at is null;
  if v_card.id is null then raise exception 'De gedeelde kaart bestaat niet meer.'; end if;

  if v_card.owner_id <> auth.uid() then
    if not exists (
      select 1 from public.card_share_members
      where shared_card_id = p_shared_card_id
        and recipient_id = auth.uid()
        and revoked_at is null
        and removed_by_recipient_at is null
    ) then
      raise exception 'Je hebt geen toegang tot deze kaart.';
    end if;
    if not public.has_paskluis_plus(auth.uid())
       or not public.has_paskluis_plus(v_card.owner_id) then
      raise exception 'Beide gebruikers hebben PasKluis Plus nodig om te bewerken.';
    end if;
  end if;

  update public.shared_cards
  set card_payload = p_card_payload,
      version = version + 1,
      updated_at = now(),
      updated_by = auth.uid()
  where id = p_shared_card_id
    and version = p_expected_version
  returning version into v_next_version;
  if v_next_version is null then
    raise exception 'De kaart is ondertussen gewijzigd. Vernieuw de kaart en probeer opnieuw.';
  end if;

  insert into public.card_share_events (shared_card_id, actor_id, action, version)
  values (p_shared_card_id, auth.uid(), 'updated', v_next_version);
  return v_next_version;
end;
$$;

create or replace function public.revoke_shared_card_access(p_membership_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_card_id uuid;
begin
  update public.card_share_members member
  set revoked_at = now()
  from public.shared_cards card
  where member.id = p_membership_id
    and member.shared_card_id = card.id
    and card.owner_id = auth.uid()
  returning member.shared_card_id into v_card_id;
  if v_card_id is null then raise exception 'Gedeelde toegang niet gevonden.'; end if;
  insert into public.card_share_events (shared_card_id, actor_id, action)
  values (v_card_id, auth.uid(), 'revoked');
end;
$$;

create or replace function public.revoke_all_shared_card_access(
  p_card_external_id text
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_card_id uuid;
begin
  select id into v_card_id from public.shared_cards
  where owner_id = auth.uid() and card_external_id = p_card_external_id;
  if v_card_id is null then return; end if;
  update public.card_share_members
  set revoked_at = now()
  where shared_card_id = v_card_id and revoked_at is null;
  update public.shared_cards set deleted_at = now() where id = v_card_id;
  insert into public.card_share_events (shared_card_id, actor_id, action)
  values (v_card_id, auth.uid(), 'revoked');
end;
$$;

create or replace function public.remove_received_shared_card(
  p_membership_id uuid
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_card_id uuid;
begin
  update public.card_share_members
  set removed_by_recipient_at = now()
  where id = p_membership_id
    and recipient_id = auth.uid()
    and revoked_at is null
  returning shared_card_id into v_card_id;
  if v_card_id is null then raise exception 'Gedeelde kaart niet gevonden.'; end if;
  insert into public.card_share_events (shared_card_id, actor_id, action)
  values (v_card_id, auth.uid(), 'removed');
end;
$$;

revoke all on function public.is_shared_card_owner(uuid, uuid) from public;
revoke all on function public.is_active_shared_card_recipient(uuid, uuid) from public;
revoke all on function public.has_paskluis_plus(uuid) from public;
revoke all on function public.share_card_by_email(text, text, text, jsonb) from public;
revoke all on function public.update_shared_card(uuid, bigint, jsonb) from public;
revoke all on function public.revoke_shared_card_access(uuid) from public;
revoke all on function public.revoke_all_shared_card_access(text) from public;
revoke all on function public.remove_received_shared_card(uuid) from public;

grant select on public.shared_cards, public.card_share_members, public.card_share_events to authenticated;
grant execute on function public.is_shared_card_owner(uuid, uuid) to authenticated;
grant execute on function public.is_active_shared_card_recipient(uuid, uuid) to authenticated;
grant execute on function public.has_paskluis_plus(uuid) to authenticated;
grant execute on function public.share_card_by_email(text, text, text, jsonb) to authenticated;
grant execute on function public.update_shared_card(uuid, bigint, jsonb) to authenticated;
grant execute on function public.revoke_shared_card_access(uuid) to authenticated;
grant execute on function public.revoke_all_shared_card_access(text) to authenticated;
grant execute on function public.remove_received_shared_card(uuid) to authenticated;
